language: android
dist: trusty
jdk: oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - build-tools-29.0.0

    # The SDK version used to compile your project
    - android-29



